kind: Namespace
apiVersion: v1
metadata:
  name: fauxmetheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: fauxmetheus
    app.kubernetes.io/version: v0.9.0
  name: fauxmetheus
  namespace: fauxmetheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fauxmetheus
  template:
    metadata:
      labels:
        app: fauxmetheus
    spec:
      containers:
      - args:
        - small.json
        image: ghcr.io/alpeb/fauxmetheus:latest
        imagePullPolicy: Always
        name: linkerd-proxy
        ports:
        - containerPort: 4191
          name: linkerd-admin
